/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_security_audio_DetectionJni */

#ifndef _Included_com_security_audio_DetectionJni
#define _Included_com_security_audio_DetectionJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_security_audio_DetectionJni
 * Method:    audioDetection
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_security_audio_DetectionJni_audioDetection
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
